# Generated by Django 3.1.2 on 2020-10-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('extra_feild', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserActivity.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
