# Generated by Django 3.0.7 on 2020-07-04 15:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=150)),
                ('souce_bus_stand_location', models.CharField(max_length=150)),
                ('destination_bus_stand_location', models.CharField(max_length=150)),
                ('passanger_capacity', models.CharField(max_length=150)),
                ('per_passanger_price', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_email', models.EmailField(max_length=150)),
                ('driver_phone_no', models.IntegerField()),
                ('driver_adress', models.CharField(max_length=150)),
                ('driver_licence', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_registration_number', models.IntegerField()),
                ('engine_number', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('number_of_seats', models.CharField(max_length=20)),
                ('fuel_capacity', models.IntegerField()),
                ('owner_name', models.CharField(max_length=150)),
                ('ac', models.BooleanField()),
                ('non_ac', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('desstination_time', models.TimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BusService')),
            ],
        ),
        migrations.AddField(
            model_name='busservice',
            name='driver_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.DriverDetail'),
        ),
        migrations.AddField(
            model_name='busservice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.VehicalDetail'),
        ),
    ]
